/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/restaurants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得所有餐廳清單 */
        get: operations["getRestaurants"];
        put?: never;
        /** 新增餐廳 */
        post: operations["createRestaurant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/my/random/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 重置抽籤池 */
        post: operations["clearMyGroupRandomPool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/my/transfer-admin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 移轉群組管理權 */
        post: operations["transferGroupAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/my/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得自己所屬群組成員清單 */
        get: operations["getMyGroupMembers"];
        put?: never;
        /** 新增群組成員 */
        post: operations["addGroupMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/my/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 自行退出群組 */
        post: operations["leaveMyGroup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增餐點 */
        post: operations["createDish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 註冊 */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 登入 */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 依餐廳 ID 取得自己所屬群組的單筆餐廳資訊 */
        get: operations["getRestaurant"];
        put?: never;
        post?: never;
        /** 刪除餐廳（軟刪除） */
        delete: operations["deleteRestaurant"];
        options?: never;
        head?: never;
        /** 修改餐廳 */
        patch: operations["updateRestaurant"];
        trace?: never;
    };
    "/restaurants/my/choose/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 確認選擇餐廳並重置抽籤池 */
        patch: operations["chooseMyGroupRestaurant"];
        trace?: never;
    };
    "/groups/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得目前群組名稱 */
        get: operations["getMyGroupProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** 修改目前群組名稱 */
        patch: operations["updateMyGroupName"];
        trace?: never;
    };
    "/restaurants/{restaurantId}/dishes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢該餐廳對應的所有餐點 */
        get: operations["getRestaurantDishes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 取得自己所屬群組的餐廳清單 */
        get: operations["getMyGroupRestaurants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/my/selection-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢自己所屬群組的餐廳選擇歷史 */
        get: operations["getMyGroupSelectionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/restaurants/my/random": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 抽取自己所屬群組的一間餐廳 */
        get: operations["getRandomMyGroupRestaurant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/my/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 刪除群組成員 */
        delete: operations["removeGroupMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dishes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 刪除餐點 */
        delete: operations["deleteDish"];
        options?: never;
        head?: never;
        /** 修改餐點 */
        patch: operations["updateDish"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateRestaurantDto: {
            /**
             * Format: int32
             * @description 所屬群組 ID
             * @example 1
             */
            groupId: number;
            /**
             * Format: int32
             * @description 餐廳分類 ID（須屬於同一群組）
             * @example 1
             */
            categoryId: number;
            /**
             * @description 餐廳名稱
             * @example 和食天國
             */
            restaurantName: string;
            /**
             * @description 備註
             * @example 可訂位
             */
            note?: string;
            /**
             * @description 圖片網址
             * @example https://example.com/restaurant.jpg
             */
            imageUrl?: string;
        };
        RestaurantResponse: {
            /**
             * Format: int32
             * @description 餐廳 ID
             * @example 1
             */
            restaurantId?: number;
            /**
             * Format: int32
             * @description 分組 ID
             * @example 1
             */
            groupId?: number;
            /**
             * Format: int32
             * @description 分類 ID
             * @example 1
             */
            categoryId?: number;
            /**
             * Format: int32
             * @description 群組內顯示排序 ID
             * @example 1
             */
            displayOrderId?: number;
            /**
             * Format: int32
             * @description 被選取次數
             * @example 10
             */
            selectedCount?: number;
            /**
             * @description 餐廳名稱
             * @example 和食天國
             */
            restaurantName?: string;
            /**
             * @description 備註
             * @example 可訂位
             */
            note?: string;
            /**
             * @description 圖片網址
             * @example https://example.com/restaurant.jpg
             */
            imageUrl?: string;
            /**
             * @description 是否封存（軟刪除）
             * @example false
             */
            isArchived?: boolean;
            /**
             * Format: date-time
             * @description 最後被選取時間
             * @example 2026-05-03 14:58:57
             */
            lastSelectedAt?: string;
            /**
             * Format: date-time
             * @description 建立時間
             * @example 2026-05-03 14:58:57
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 更新時間
             * @example 2026-05-03 14:58:57
             */
            updatedAt?: string;
        };
        TransferGroupAdminDto: {
            /**
             * Format: int32
             * @description 要移轉管理權的目標成員 userId
             * @example 15
             */
            targetUserId: number;
        };
        GroupMemberResponse: {
            /** Format: int32 */
            userId?: number;
            /** Format: int32 */
            groupId?: number;
            /** Format: int32 */
            displayOrderId?: number;
            /** Format: int32 */
            role?: number;
            username?: string;
            email?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        AddGroupMemberDto: {
            /**
             * Format: int32
             * @description 要加入群組的使用者 ID
             * @example 12
             */
            userId: number;
        };
        CreateDishDto: {
            /**
             * Format: int32
             * @description 餐點所屬餐廳 ID
             * @example 1
             */
            restaurantId: number;
            /**
             * Format: int32
             * @description 餐點價格
             * @example 130
             */
            price: number;
            /**
             * @description 餐點名稱
             * @example 牛肉拉麵
             */
            dishName: string;
        };
        DishResponse: {
            /**
             * Format: int32
             * @description 餐點 ID
             * @example 1
             */
            dishId?: number;
            /**
             * Format: int32
             * @description 餐點對應餐廳編號
             * @example 1
             */
            restaurantId?: number;
            /**
             * Format: int32
             * @description 餐廳群組內順序 ID
             * @example 1
             */
            displayOrderId?: number;
            /**
             * Format: int32
             * @description 價格
             * @example 120
             */
            price?: number;
            /**
             * @description 餐點名稱
             * @example 豚骨拉麵
             */
            dishName?: string;
        };
        RegisterRequest: {
            /**
             * Format: int32
             * @description 使用者角色
             * @example 2
             */
            role?: number;
            /**
             * @description 使用者名稱
             * @example test
             */
            username: string;
            /**
             * @description 電子郵件
             * @example test@test.com
             */
            email: string;
            /**
             * @description 密碼
             * @example 123
             */
            password: string;
        };
        LoginResponse: {
            /** Format: int32 */
            userId?: number;
            /** Format: int32 */
            groupId?: number;
            /** Format: int32 */
            role?: number;
            username?: string;
            email?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            token?: string;
        };
        LoginRequest: {
            /**
             * @description 電子郵件
             * @example super@test.com
             */
            email: string;
            /**
             * @description 密碼
             * @example 123
             */
            password: string;
        };
        UpdateRestaurantDto: {
            /**
             * Format: int32
             * @description 餐廳分類 ID（須屬於餐廳既有群組）
             * @example 1
             */
            categoryId?: number;
            /**
             * Format: int32
             * @description 群組內顯示排序 ID
             * @example 1
             */
            displayOrderId?: number;
            /**
             * Format: int32
             * @description 被選取次數
             * @example 10
             */
            selectedCount?: number;
            /**
             * @description 餐廳名稱
             * @example 和食天國
             */
            restaurantName?: string;
            /**
             * @description 備註
             * @example 可訂位
             */
            note?: string;
            /**
             * @description 圖片網址
             * @example https://example.com/restaurant.jpg
             */
            imageUrl?: string;
            /**
             * Format: date-time
             * @description 最後被選取時間
             * @example 2026-05-03 14:58:57
             */
            lastSelectedAt?: string;
        };
        UpdateGroupNameDto: {
            /**
             * @description 群組名稱
             * @example 新的午餐小隊
             */
            groupName: string;
        };
        GroupProfileResponse: {
            /** Format: int32 */
            groupId?: number;
            groupName?: string;
        };
        UpdateDishDto: {
            /**
             * Format: int32
             * @description 餐廳群組內順序 ID
             * @example 1
             */
            displayOrderId: number;
            /**
             * @description 餐點名稱
             * @example 雙倍叉燒拉麵
             */
            dishName: string;
            /**
             * Format: int32
             * @description 餐點價格
             * @example 180
             */
            price: number;
        };
        RestaurantListResponseRestaurantResponse: {
            data?: components["schemas"]["RestaurantResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            total?: number;
        };
        DishListResponse: {
            data?: components["schemas"]["DishResponse"][];
            /** Format: int32 */
            total?: number;
        };
        RestaurantListResponseSelectionHistoryResponse: {
            data?: components["schemas"]["SelectionHistoryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            limit?: number;
            /** Format: int64 */
            total?: number;
        };
        SelectionHistoryResponse: {
            /** Format: int32 */
            historyId?: number;
            /** Format: int32 */
            restaurantId?: number;
            restaurantName?: string;
            category?: string;
            /** Format: date-time */
            selectedAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getRestaurants: {
        parameters: {
            query?: {
                /** @description 群組 ID */
                groupId?: number;
                /** @description 分類 ID */
                categoryId?: number;
                /** @description 是否已刪除 */
                isArchived?: boolean;
                /** @description 搜尋關鍵字 */
                search?: string;
                /** @description 排序欄位 */
                orderBy?: "RESTAURANT_ID" | "CATEGORY_ID" | "DISPLAY_ORDER_ID" | "SELECTED_COUNT" | "RESTAURANT_NAME" | "LAST_SELECTED_AT" | "CREATED_AT" | "UPDATED_AT";
                /** @description 排序方向 */
                sort?: "ASC" | "DESC";
                /** @description 頁碼 */
                page?: number;
                /** @description 每頁筆數 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantListResponseRestaurantResponse"];
                };
            };
        };
    };
    createRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRestaurantDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    clearMyGroupRandomPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    transferGroupAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferGroupAdminDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupMemberResponse"];
                };
            };
        };
    };
    getMyGroupMembers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupMemberResponse"][];
                };
            };
        };
    };
    addGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddGroupMemberDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupMemberResponse"];
                };
            };
        };
    };
    leaveMyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createDish: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDishDto"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    getRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    deleteRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    updateRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRestaurantDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    chooseMyGroupRestaurant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    getMyGroupProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupProfileResponse"];
                };
            };
        };
    };
    updateMyGroupName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupNameDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["GroupProfileResponse"];
                };
            };
        };
    };
    updateDish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDishDto"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishResponse"];
                };
            };
        };
    };
    getRestaurantDishes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                restaurantId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DishListResponse"];
                };
            };
        };
    };
    getMyGroupRestaurants: {
        parameters: {
            query?: {
                /** @description 群組 ID */
                groupId?: number;
                /** @description 分類 ID */
                categoryId?: number;
                /** @description 是否已刪除 */
                isArchived?: boolean;
                /** @description 搜尋關鍵字 */
                search?: string;
                /** @description 排序欄位 */
                orderBy?: "RESTAURANT_ID" | "CATEGORY_ID" | "DISPLAY_ORDER_ID" | "SELECTED_COUNT" | "RESTAURANT_NAME" | "LAST_SELECTED_AT" | "CREATED_AT" | "UPDATED_AT";
                /** @description 排序方向 */
                sort?: "ASC" | "DESC";
                /** @description 頁碼 */
                page?: number;
                /** @description 每頁筆數 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantListResponseRestaurantResponse"];
                };
            };
        };
    };
    getMyGroupSelectionHistory: {
        parameters: {
            query?: {
                /** @description 頁碼 */
                page?: number;
                /** @description 每頁筆數 */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantListResponseSelectionHistoryResponse"];
                };
            };
        };
    };
    getRandomMyGroupRestaurant: {
        parameters: {
            query?: {
                categoryId?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RestaurantResponse"];
                };
            };
        };
    };
    removeGroupMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteDish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
