# H2 檔案庫：./data/mogumogu
spring.datasource.url=jdbc:h2:file:./data/mogumogu;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console
spring.h2.console.enabled=true

# 不用 schema/data.sql，交給 Flyway
spring.sql.init.mode=never
