# 匯入 .env
spring.config.import=optional:file:.env[.properties]

# 應用程式名稱
spring.application.name=mogumogu

# Profile 預設 h2；
spring.profiles.active=${SPRING_PROFILES_ACTIVE:h2}

# Jackson 日期格式、時區
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

# 伺服器 port 號碼
server.port=${PORT:8080}

# 內建錯誤回應包含可讀訊息
server.error.include-message=always
server.error.include-binding-errors=always

# Flyway 依 vendor（h2/mysql）載入 migration
spring.flyway.locations=classpath:db/migration/{vendor}
