CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    group_id           INT NOT NULL,
    display_order      INT NOT NULL,
    restaurant_name    VARCHAR(64) NOT NULL,
    category           VARCHAR(32) NOT NULL,
    image_url          VARCHAR(512),
    selected_count     INT NOT NULL DEFAULT 0,
    last_selected_at   TIMESTAMP,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    note               VARCHAR(512)
);