CREATE TABLE IF NOT EXISTS "user" (
    user_id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    group_id             INT NOT NULL,
    display_order_id     INT NOT NULL,
    username             VARCHAR(64) NOT NULL,
    user_password        VARCHAR(255) NOT NULL,
    roles                INT NOT NULL DEFAULT 2,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    email                VARCHAR(255) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);
