CREATE TABLE IF NOT EXISTS restaurant_categories (
    category_id      INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    group_id         INT NOT NULL,
    display_order    INT NOT NULL,
    category_name    VARCHAR(32) NOT NULL,
    CONSTRAINT uk_restaurant_categories_group_name UNIQUE (group_id, category_name)
);

ALTER TABLE restaurants
    ALTER COLUMN category RENAME TO category_id;
