CREATE TABLE "user_new" (
    user_id              INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
    group_id             INT,
    display_order_id     INT NOT NULL,
    roles                INT NOT NULL DEFAULT 2,
    username             VARCHAR(64) NOT NULL,
    user_password        VARCHAR(255) NOT NULL,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    email                VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO "user_new" (user_id, group_id, display_order_id, roles, username, user_password, created_at, updated_at, email)
SELECT user_id, group_id, display_order_id, roles, username, user_password, created_at, updated_at, email
FROM "user";

DROP TABLE "user";
ALTER TABLE "user_new" RENAME TO "user";
